name: publish-python-package
run-name: fracsuite-lib publish
on:
  push:
    paths:
      - 'conner/**.toml'
jobs:
  build_job:
    container:
      image: localhost/fracsuite-lib-image
    steps:
    - uses: actions/checkout@v2

    - name: Check Version Change
      run: |
        git diff HEAD~1 -- conner/Cargo.toml | grep "\+version" || exit 1

    - name: Publish
      run: |
        cd conner
        maturin publish --username __token__ --password ${{ secrets.PYPI_TOKEN }} --target x86_64-pc-windows-gnu -i python3.10
