name: publish-python-package
run-name: fracsuite-lib publish
on:
  push:
    paths:
      - 'splintaz/**.toml'
jobs:
  Publish Splintaz:
    container:
      image: localhost/fracsuite-lib-image
    steps:
    - uses: actions/checkout@v2

    - name: Publish
      run: |
        cd splintaz
        maturin publish --username __token__ --password ${{ secrets.PYPI_FULLTOKEN }} --target x86_64-pc-windows-gnu -i python3.10
