# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Common system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    build-essential \
    ca-certificates \
    gnupg \
    git \
    mingw-w64 \
	clang \
	libclang-dev \
	libopencv-dev 

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="$PATH:/root/.cargo/bin"

RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
RUN apt-get update && apt-get install -y nodejs

RUN rustup default stable
RUN rustup target add x86_64-pc-windows-gnu
RUN cargo install maturin

RUN export OPENCV_INCLUDE_PATHS="/usr/include/"
RUN export OPENCV_LINK_PATHS="/usr/lib/x86_64-linux-gnu/"
RUN export OPENCV_LINK_LIBS="opencv_core,opencv_imgproc"